<?php

/**
 * @file
 * Functions to support wienimal admin toolbar.
 */
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_html().
 */
function wienimal_admin_toolbar_preprocess_html(&$variables)
{
    // Add 'wienimal-admin-toolbar' class to the body.
    if (_wienimal_admin_toolbar_is_access()) {
        $variables['attributes']['class'][] = 'wienimal-admin-toolbar';
    }
}

/**
 * Implements hook_page_attachments_alter().
 */
function wienimal_admin_toolbar_page_attachments_alter(array &$page)
{
    if (_wienimal_admin_toolbar_is_access()) {
        // Attach the icons.
        $page['#attached']['library'][] = 'wienimal_admin_toolbar/ionicons';
        // Attach the custom css.
        $page['#attached']['library'][] = 'wienimal_admin_toolbar/wienimal-admin-toolbar';
    }
}

/**
 * Implements hook_toolbar().
 */
function wienimal_admin_toolbar_toolbar()
{
    if ($json_data = _wienimal_admin_toolbar_read_build_info()) {
        $items = [];

        $data = json_decode($json_data);

        $items['build_info'] = [
            '#type' => 'toolbar_item',
            'tab' => [
                '#type' => 'link',
                '#title' => $data->version . ' (' . date_format(date_add(date_create($data->date), date_interval_create_from_date_string('1 hour')), 'd/m/y - h:i') . ')',
                '#url' => Url::fromRoute('<front>'),
                '#options' => [
                    'attributes' => [
                        'title' => t('Home page'),
                        'class' => ['toolbar-item', 'toolbar-deploy'],
                    ],
                ],
            ],
            '#weight' => 1000,
            '#wrapper_attributes' => [
                'class' => ['right-toolbar-tab'],
            ],
        ];

        return $items;
    }
}

/**
 * Helper function to read the version data.
 *
 * @return string or false if no data
 */
function _wienimal_admin_toolbar_read_build_info()
{
    return @file_get_contents('./version.json');
}


/**
 * Implements hook_toolbar_alter().
 */
function wienimal_admin_toolbar_toolbar_alter(&$items)
{
    // Add class to the user tab so it can be moved to the right.
    if (_wienimal_admin_toolbar_is_access()) {
        $items['user']['#wrapper_attributes']['class'] = ['right-toolbar-tab'];
    }
}

/**
 * Helper function for checking user permission.
 * We really only want to add styling and changes to toolbar when the user has
 * access.
 *
 * Returns TRUE or FALSE.
 */
function _wienimal_admin_toolbar_is_access()
{
    $user = \Drupal::currentUser();
    return $user->hasPermission('access toolbar');
}

/**
 * Implements hook_library_info_alter().
 */
function wienimal_admin_toolbar_library_info_alter(&$libraries, $extension)
{

    $styles_path = '/' . drupal_get_path('module', 'wienimal_admin_toolbar') . '/css';

    if ($extension == 'toolbar' && isset($libraries['toolbar'])) {
        $new_css = [];
        $replacements = [
            'css/toolbar.theme.css' => $styles_path . '/toolbar.theme.css',
            'css/toolbar.icons.theme.css' => $styles_path . '/toolbar.icons.theme.css',
        ];

        foreach ($libraries['toolbar']['css']['theme'] as $source => $options) {
            if (isset($replacements[$source])) {
                $new_css[$replacements[$source]] = $options;
            } else {
                $new_css[$source] = $options;
            }
        }
        $libraries['toolbar']['css']['theme'] = $new_css;
    }

    if ($extension == 'admin_toolbar' && isset($libraries['toolbar.tree'])) {
        $new_css = [];
        $replacements = [
            'css/admin.toolbar.css' => $styles_path . '/admin.toolbar.css',
        ];

        foreach ($libraries['toolbar.tree']['css']['theme'] as $source => $options) {
            if (isset($replacements[$source])) {
                $new_css[$replacements[$source]] = $options;
            } else {
                $new_css[$source] = $options;
            }
        }
        $libraries['toolbar.tree']['css']['theme'] = $new_css;
    }
}

/**
 * Implements hook_preprocess_toolbar().
 */
function wienimal_admin_toolbar_preprocess_toolbar(&$variables)
{
    // Lock the toolbar
    // $variables['#attached']['library'][] = 'wienimal_admin_toolbar/toolbar.lock';
    // Pass the module directory to the Twig files, like the directory variable in themes.
    $variables['module_directory'] = drupal_get_path('module', 'wienimal_admin_toolbar');
    // Admin logo
    $variables['admin_logo_path'] = _wienimal_admin_toolbar_admin_logo_path();

    if (\Drupal::config('wienimal.settings')->get('toolbar.theme') == 'dark') {
        $variables['#attached']['library'][] = 'wienimal_admin_toolbar/wienimal.toolbar.dark';
    }
}

/**
 * Helper function to get the admin logo
 */
function _wienimal_admin_toolbar_admin_logo_path()
{
    // The default logo from this module.
    $admin_logo_module_path = '/' . drupal_get_path('module', 'wienimal_admin_toolbar') . '/admin-logo.svg';

    // Get the active theme.
    $theme = \Drupal::config('system.theme')->get('default');
    $admin_logo_theme_path = drupal_get_path('theme', $theme) . '/admin-logo.svg';

    // Return the admin logo from the front-end theme if there is one. Otherwise
    // return the default logo.
    if (file_exists($admin_logo_theme_path)) {
        return $admin_logo_theme_path;
    } else {
        return $admin_logo_module_path;
    }
}

function wienimal_admin_toolbar_theme_suggestions_menu_alter(array &$suggestions, array $variables)
{
    if (isset($variables['menu_name']) && $variables['menu_name'] == 'devel') {
        $suggestions[] = 'menu__toolbar';
    }
}

/**
 * Implements hook_theme_registry_alter().
 */
function wienimal_admin_toolbar_theme_registry_alter(&$theme_registry)
{
    $theme_registry['toolbar']['path'] = drupal_get_path('module', 'wienimal_admin_toolbar') . '/templates';
}
